services:
  backend:
    container_name: back
    build: .
    ports:
      - "3333:3333"
    environment:
      RAILS_ENV: production
      POSTGRES_HOST: db
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: sq159aw753
    volumes:
      - .:/app:cached
    depends_on:
      - db
      - db_test
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: sq159aw753
      POSTGRES_DB: porcupine_database
    volumes:
      - pgdata:/var/lib/postgresql/data

  db_test:
    image: postgres:15
    container_name: db_test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: sq159aw753
      POSTGRES_DB: porcupine_database_test
    volumes:
      - pgdata_test:/var/lib/postgresql/data

volumes:
  pgdata:
  pgdata_test:
