services:
  backend:
    build: .
    ports:
      - "3333:3333"
    environment:
      RAILS_ENV: production
      POSTGRES_HOST: db
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: sq159aw753
    volumes:
      - .:/app:cached
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: sq159aw753
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: