services:
  backend:
    container_name: back
    build: .
    env_file:
      - .env.production
    ports:
      - "3333:3333"
    volumes:
      - .:/app:cached
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    env_file:
      - .env.db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
