default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["POSTGRES_DB"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>
  pool: 5


development:
  <<: *default
  database: porcupine_database

test:
  <<: *default
  database: porcupine_database

production:
  <<: *default
  database: porcupine_database
