default: &default
  adapter: postgresql
  encoding: unicode
  username: backend_user
  password: sq159aw753
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: porcupine_database 

test:
  <<: *default
  database: porcupine_database-test

production:
  <<: *default
  database: porcupine_database